language: node_js
sudo: required
addons:
    chrome: stable
node_js:
    - 9
before_install:
    - yarn
    - cd publish/samplesite/instrumentation-tests && yarn
install:
    - npm run build
script:
    - xvfb-run npm run test
    - xvfb-run npm run instrumentation
cache:
    yarn: true
deploy:
    provider: pages
    skip-cleanup: true
    github-token: $GITHUB_TOKEN
    keep-history: true
    on:
        branch: master
    local-dir: ./dist/roosterjs
